replicaCount: 1

image:
  repository: registry.deepmemo-app.deep.foundation/deepmemo-app
  tag: "latest"
  pullPolicy: Always

imagePullSecrets: false
nameOverride: "deepmemo-app"
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "deepmemo-app"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  protocol: TCP
  port: 80
  targetPort: 3000

containerPort: 3000

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: deepmemo.deep.foundation
      paths:
        path: /
  tls:
    - hosts:
        - deepmemo.deep.foundation
      secretName: deepmemo-tls

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1

nodeSelector: {}

tolerations: []

affinity: {}
